const rabbitBreeds = [
    "American",
    "Belgian Hare",
    "Beveren",
    "Britannia Petite",
    "Californian",
    "Champagne d'Argent",
    "Checkered Giant",
    "Cinnamon",
    "Dutch",
    "English Angora",
    "English Lop",
    "English Spot",
    "Flemish Giant",
    "Florida White",
    "French Angora",
    "French Lop",
    "Giant Angora",
    "Harlequin",
    "Havana",
    "Himalayan",
    "Holland Lop",
    "Hotot",
    "Jersey Wooly",
    "Lilac",
    "Lionhead",
    "Mini Lop",
    "Mini Rex",
    "Mixed",
    "Netherland Dwarf",
    "New Zealand",
    "Palomino",
    "Polish",
    "Rex",
    "Rhinelander",
    "Satin",
    "Silver",
    "Silver Fox",
    "Silver Marten",
    "Tan",
    "Thrianta",
  ];
  export default rabbitBreeds;
